### listar todos estudantes
GET http://localhost:3000/estudante

### listar um estudante
GET http://localhost:3000/estudante/1

### criar estudante
POST http://localhost:3000/estudante
Content-Type: application/json

{
    "nome": "leticia",
    "matricula": "RA1234",
    "email": "Leticia@gmail.com",
    "dt_nascimento": "2000-11-11",
    "cidade_id": 1
}
### atulizar estudantes
PATCH http://localhost:3000/estudante/1
Content-Type: application/json

{
    
}
### apagar estudantes
DELETE http://localhost:3000/estudante/1
